
package gui;

import javax.swing.ComboBoxModel;
public class PropriedadesTopologia extends javax.swing.JFrame {
    
    /** Creates new form PropriedadesNo */
    public PropriedadesTopologia(String nomeTopologia) {
        initComponents();
        initOtherComponents(nomeTopologia);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWCRexp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelWCRexp3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelWCR = new javax.swing.JLabel();
        jLabelWCRTotal = new javax.swing.JLabel();
        jLabelNumConversores = new javax.swing.JLabel();
        jLabelTx = new javax.swing.JLabel();
        jLabelRx = new javax.swing.JLabel();
        jComboBoxWCR = new javax.swing.JComboBox();
        jComboBoxWCRTotal = new javax.swing.JComboBox();
        jSpinnerNConversores = new javax.swing.JSpinner();
        jComboBoxTx = new javax.swing.JComboBox();
        jComboBoxRx = new javax.swing.JComboBox();
        jButtonAplicar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNoProp = new javax.swing.JTextArea();
        jLabelPeso = new javax.swing.JLabel();
        jSpinnerPeso = new javax.swing.JSpinner();

        setTitle("Propriedades do Nó");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(297, 381));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jLabelWCRexp.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabelWCRexp3.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelWCR.setText("WCR :");

        jLabelWCRTotal.setText("WCR TOTAL :");
        jLabelWCRTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNumConversores.setText("WCs :");

        jLabelTx.setText("Tx :");

        jLabelRx.setText("Rx :");

        jComboBoxWCR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "false", "true" }));
        jComboBoxWCR.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxWCRItemStateChanged(evt);
            }
        });

        jComboBoxWCRTotal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "false", "true" }));
        jComboBoxWCRTotal.setEnabled(false);
        jComboBoxWCRTotal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxWCRTotalItemStateChanged(evt);
            }
        });

        jSpinnerNConversores.setEditor(jSpinnerNConversores.getEditor());
        jSpinnerNConversores.setEnabled(false);

        jComboBoxTx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ilimitado" }));
        jComboBoxTx.setEnabled(false);

        jComboBoxRx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ilimitado" }));
        jComboBoxRx.setEnabled(false);

        jButtonAplicar.setText("Aplicar");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });

        jTextAreaNoProp.setColumns(20);
        jTextAreaNoProp.setEditable(false);
        jTextAreaNoProp.setFont(new java.awt.Font("Courier", 0, 11));
        jTextAreaNoProp.setLineWrap(true);
        jTextAreaNoProp.setRows(3);
        jTextAreaNoProp.setTabSize(4);
        jTextAreaNoProp.setText("WCR = Nó com Capacidade de Conversão de Comprimento de Onda. WCR TOTAL = Nó com Capacidade de Conversão Total. WCs: Número de Conversores de Comprimento de Onda. Tx = Transmissores. Rx = Receptores.");
        jTextAreaNoProp.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaNoProp);

        jLabelPeso.setText("Peso :");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(82, 82, 82)
                        .add(jLabelWCR)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBoxWCR, 0, 212, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(47, 47, 47)
                        .add(jLabelWCRTotal)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBoxWCRTotal, 0, 212, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(84, 84, 84)
                        .add(jLabelNumConversores)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSpinnerNConversores, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabelTx)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jComboBoxTx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelRx)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jComboBoxRx, 0, 203, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(93, 93, 93)
                                .add(jLabelPeso)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jSpinnerPeso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(264, Short.MAX_VALUE)
                        .add(jButtonAplicar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxWCR, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelWCR))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxWCRTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelWCRTotal))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelNumConversores)
                    .add(jSpinnerNConversores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelTx)
                    .add(jComboBoxTx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelRx)
                    .add(jComboBoxRx, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jSpinnerPeso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelPeso))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonAplicar)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxWCRItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxWCRItemStateChanged
        if (this.jComboBoxWCR.getSelectedItem().toString().equalsIgnoreCase("false")){
            this.jComboBoxWCRTotal.setEnabled(false);
            this.jSpinnerNConversores.setEnabled(false);
        }else{            
            this.jComboBoxWCRTotal.setEnabled(true);
            this.jSpinnerNConversores.setEnabled(true);            
        }

    }//GEN-LAST:event_jComboBoxWCRItemStateChanged

    private void jComboBoxWCRTotalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxWCRTotalItemStateChanged
        if (this.jComboBoxWCRTotal.getSelectedItem().toString().equalsIgnoreCase("false")){            
            this.jSpinnerNConversores.setEnabled(true);
        }else{            
            this.jSpinnerNConversores.setEnabled(false);            
        }
    }//GEN-LAST:event_jComboBoxWCRTotalItemStateChanged

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        
        
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAplicarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated
    
    private void initOtherComponents(String nomeTopologia) {

        
        this.setTitle("Propriedades da Topologia " + nomeTopologia);
        
        ComboBoxModel cbmWCR = this.jComboBoxWCR.getModel();
        ComboBoxModel cbmWCRTotal = this.jComboBoxWCRTotal.getModel();
       
        cbmWCR.setSelectedItem(cbmWCR.getElementAt(0));//false.
        this.jComboBoxWCRTotal.setEnabled(false);
        this.jSpinnerNConversores.setEnabled(false);
       
        this.jSpinnerPeso.setValue(1);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JComboBox jComboBoxRx;
    private javax.swing.JComboBox jComboBoxTx;
    private javax.swing.JComboBox jComboBoxWCR;
    private javax.swing.JComboBox jComboBoxWCRTotal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNumConversores;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelRx;
    private javax.swing.JLabel jLabelTx;
    private javax.swing.JLabel jLabelWCR;
    private javax.swing.JLabel jLabelWCRTotal;
    private javax.swing.JLabel jLabelWCRexp;
    private javax.swing.JLabel jLabelWCRexp3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerNConversores;
    private javax.swing.JSpinner jSpinnerPeso;
    private javax.swing.JTextArea jTextAreaNoProp;
    // End of variables declaration//GEN-END:variables
    private NoGrf no;
}
