/*
 * PropriedadesLink.java
 *
 * Created on July 27, 2007, 6:22 PM
 */

package gui;

import java.awt.Dimension;

/**
 *
 * @author  Gil
 */
public class PropriedadesLink extends javax.swing.JFrame {
    
    /** Creates new form PropriedadesLink */
    public PropriedadesLink(Topologia topologia, int indexOfLink) {
        initComponents();
        initOtherComponents(topologia,indexOfLink);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelOrigem = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelBidirecional = new javax.swing.JLabel();
        jLabelW = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldOrigem = new javax.swing.JTextField();
        jTextFieldDestino = new javax.swing.JTextField();
        jComboBoxBidirecinal = new javax.swing.JComboBox();
        jSpinnerW = new javax.swing.JSpinner();
        jButtonAplicar = new javax.swing.JButton();
        jLabelCusto = new javax.swing.JLabel();
        jSpinnerCuto = new javax.swing.JSpinner();
        jLDistLink = new javax.swing.JLabel();
        jSpDistLink = new javax.swing.JSpinner();

        setTitle("Propriedades do Link");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNome.setText("Nome:");

        jLabelOrigem.setText("Origem:");

        jLabelDestino.setText("Destino:");

        jLabelBidirecional.setText("Bidirecional:");

        jLabelW.setText("Número de comprimentos de onda:");
        jLabelW.setToolTipText("número de comprimentos de onda");

        jTextFieldNome.setEditable(false);

        jTextFieldOrigem.setEditable(false);

        jTextFieldDestino.setEditable(false);

        jComboBoxBidirecinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "false" }));

        jButtonAplicar.setText("Aplicar");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });

        jLabelCusto.setText("Custo:");

        jLDistLink.setText("Distância:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabelNome)
                                    .add(jLabelBidirecional)
                                    .add(jLDistLink))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldNome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .add(jComboBoxBidirecinal, 0, 71, Short.MAX_VALUE)
                                    .add(jSpDistLink, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jLabelOrigem)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jTextFieldOrigem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelDestino)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabelCusto))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSpinnerW)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSpinnerCuto)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextFieldDestino, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))))
                            .add(jLabelW, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jButtonAplicar)
                        .add(90, 90, 90))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelOrigem)
                    .add(jTextFieldOrigem, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelNome)
                    .add(jTextFieldNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldDestino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelDestino)
                    .add(jLabelBidirecional)
                    .add(jComboBoxBidirecinal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jSpinnerCuto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelCusto)
                    .add(jSpDistLink, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLDistLink))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelW)
                    .add(jSpinnerW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonAplicar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        if (this.jComboBoxBidirecinal.getSelectedIndex()==0){
            this.topologia.setLinkBidirecional(this.indexOfLink,true);
        }else{
            this.topologia.setLinkBidirecional(this.indexOfLink,false);
        }
        System.out.println("............"+this.jSpinnerCuto.getValue());
        Double d = new Double((Integer)this.jSpinnerCuto.getValue());
        this.topologia.setCostOfLink(this.indexOfLink,d);
        this.topologia.setNumWaveOfLink(this.indexOfLink,(Integer)this.jSpinnerW.getModel().getValue());
        this.topologia.setDistanceOfLink(this.indexOfLink,((Double)this.jSpDistLink.getModel().getValue()).intValue());
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAplicarActionPerformed
    

    private void initOtherComponents(Topologia topologia, int indexOfLink) {
        this.topologia=topologia;
        this.indexOfLink=indexOfLink;
        LinkGrf linkG=topologia.getLink(indexOfLink);
        this.setTitle("Link "+linkG.getId());      //titulo
        this.jTextFieldNome.setText(linkG.getName());              //nome do link
        this.jTextFieldOrigem.setText(linkG.getNoOrigem().getName());//origem
        this.jTextFieldDestino.setText(linkG.getNoDestino().getName());//destino  
        if (linkG.isBidirecional()){
            this.jComboBoxBidirecinal.setSelectedIndex(0);      //bidirecional
        }
        else{
            this.jComboBoxBidirecinal.setSelectedIndex(1);      //unidirecional
        }
        this.jSpinnerCuto.getModel().setValue(((Number)linkG.getCost()).intValue());//custo
        this.jSpinnerW.getModel().setValue((Number)linkG.getNumWave());//num wavelength
        this.jSpDistLink.getModel().setValue(linkG.getDistance());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JComboBox jComboBoxBidirecinal;
    private javax.swing.JLabel jLDistLink;
    private javax.swing.JLabel jLabelBidirecional;
    private javax.swing.JLabel jLabelCusto;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelOrigem;
    private javax.swing.JLabel jLabelW;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpDistLink;
    private javax.swing.JSpinner jSpinnerCuto;
    private javax.swing.JSpinner jSpinnerW;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldOrigem;
    // End of variables declaration//GEN-END:variables

   private Topologia topologia;
   private int indexOfLink;

    
}
